from . import Frame as Frame
from . import Traceback as Traceback

def unpickle_traceback(tb_frame, tb_lineno, tb_next): ...
def pickle_traceback(tb): ...
def unpickle_exception(func, args, cause, tb): ...
def pickle_exception(obj): ...
def install(*exc_classes_or_instances): ...
