# Stubs for cryptography.__about__ (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

__title__: str
__summary__: str
__uri__: str
__email__: str
__license__: str
__copyright__: Any

# Names in __all__ with no definition:
__author__: str
__version__: str
