# Stubs for cryptography (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from cryptography.__about__ import __author__ as __author__, __copyright__ as __copyright__, __email__ as __email__, __license__ as __license__, __summary__ as __summary__, __title__ as __title__, __uri__ as __uri__, __version__ as __version__
