# Stubs for OpenSSL (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from OpenSSL import SSL as SSL
from OpenSSL import crypto as crypto
from OpenSSL.version import __author__ as __author__
from OpenSSL.version import __copyright__ as __copyright__
from OpenSSL.version import __email__ as __email__
from OpenSSL.version import __license__ as __license__
from OpenSSL.version import __summary__ as __summary__
from OpenSSL.version import __title__ as __title__
from OpenSSL.version import __uri__ as __uri__
from OpenSSL.version import __version__ as __version__
