from typing import Any

logger: Any
POSITIONAL_WARNING: str
POSITIONAL_EXCEPTION: str
POSITIONAL_IGNORE: str
POSITIONAL_SET: Any
positional_parameters_enforcement = POSITIONAL_WARNING
_SYM_LINK_MESSAGE: str
_IS_DIR_MESSAGE: str
_MISSING_FILE_MESSAGE: str

def positional(max_positional_args: Any): ...
def scopes_to_string(scopes: Any): ...
def string_to_scopes(scopes: Any): ...
def parse_unique_urlencoded(content: Any): ...
def update_query_params(uri: Any, params: Any): ...
def _add_query_parameter(url: Any, name: Any, value: Any): ...
def validate_file(filename: Any) -> None: ...
def _parse_pem_key(raw_key_input: Any): ...
def _json_encode(data: Any): ...
def _to_bytes(value: Any, encoding: str = ...): ...
def _from_bytes(value: Any): ...
def _urlsafe_b64encode(raw_bytes: Any): ...
def _urlsafe_b64decode(b64string: Any): ...
