class X509:
    def get_subject(self): ...
    def get_issuer(self): ...
    def get_notAfter(self): ...
    def get_notBefore(self): ...
    def has_expired(self): ...
    def get_serial_number(self) -> int: ...
    def get_extension_count(self): ...
    def get_extension(self, index: int): ...


def load_certificate(filetype: int, buffer: bytes) -> X509: ...

FILETYPE_PEM: int
